name: "CI"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run type check
        run: pnpm run type-check

  format-check:
    name: Code Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm i

      - name: Run format check
        run: npm run format

  # unit-test:
  #   name: Unit Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 22

  #     - name: Setup pnpm
  #       run: npm i -g pnpm

  #     - name: Install dependencies
  #       run: pnpm i

  #     - name: Run tests
  #       run: npm run test
